# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
# relative_permalinks: true

# Setup
title:               Many Fox Given
# tagline:             'Because the fox nose!'
description: >- # this means to ignore newlines until "baseurl:"
  A blog on the little things in life — ethics, voting, AI, coffee,
  and programming.
baseurl:                ''
url:                  https://jeremydanielfox.github.io/
# baseurl:             '/fox-nose/'
# baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Jeremy Fox
  url:               https://twitter.com/jeremydanielfox
  email:             jeremy.daniel.fox@gmail.com

# Custom vars
version:             1.3.1

# gem: [jekyll-paginate, jekyll-gists]

# Google Analytics
google_analytics: UA-146941725-1
gems: [jekyll-paginate, jekyll-seo-tag]
paginate_path: "page:num"

# Disqus Comments
disqus:
    # Leave shortname blank to disable comments site-wide.
    # Disable comments for any post by adding `comments: false` to that post's YAML Front Matter.
    shortname: manyfoxgiven

