# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Fox Nose
tagline:             'Because the fox nose!'
description: >- # this means to ignore newlines until "baseurl:"
  A blog on the little things in life — ethics, voting, AI, coffee,
  and programming.
url:                https://jeremydanielfox.github.io/
# url:                  http://127.0.0.1:4000/
baseurl:             '/fox-nose/'
# baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Jeremy Fox
  url:               https://twitter.com/jeremydanielfox
  email:             jeremy.daniel.fox@gmail.com

# Custom vars
version:             1.0.0

gem: [jekyll-paginate, jekyll-gists]

# Google Analytics
google_analytics: UA-146941725-1